#!/bin/zsh

system_type=$(uname -s)

if [ "$(id -u)" != "0" ] && command -v sudo; then
    SUDO=sudo
fi

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "${ZDOTDIR:-$HOME}/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    brew bundle cleanup --global --force
  fi

fi

# bootstrap vim using vim-plug
if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

# configure zsh and prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git ${ZDOTDIR:-$HOME}/.zprezto

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

# don't show last login timestamp
touch ~/.hushlogin
