#!/bin/bash

system_type=$(uname -s)

if [ "$(id -u)" != "0" ] && command -v sudo; then
    SUDO=sudo
fi

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    brew bundle cleanup --global --force
  fi

  # update the iTerm2 preference directory
  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

fi

# bootstrap vim using vim-plug
if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

# configure zsh and prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git ${HOME}/.config/zsh/.zprezto
zsh ${HOME}/.yadm/bin/prezto.zsh || true
$SUDO chsh -s $(which zsh) $(whoami) >/dev/null 2>&1

